### ISSUE TITLE
Define interface

### ISSUE THREAD

**Issue by axi92** [koloo91/network-scanner#3]
network-scanner uses my docker0 interface to scan and not my Ethernet interface.
Can you add a parameter to define an interface?

In arp-scan it would be this:

```
--interface=<s> or -I <s> Use network interface <s>.
			If this option is not specified, arp-scan will search
			the system interface list for the lowest numbered,
			configured up interface (excluding loopback).
			The interface specified must support ARP.
```

**Comment by koloo91** [comment]
I will add this feature

**Comment by koloo91** [comment]
@axi92 New version 0.2.0 has this feature. You can pass additional command line arguments via options object
